### ISSUE TITLE
添加本地运行说明

### ISSUE THREAD

**Issue by awxiaoxian2020** [qk-antares/antares-blog-backend#1]
本项目使用的技术栈还是挺多的，个人建议添加本地部署方案说明，或增加 Dockerfile.

**Comment by qk-antares** [comment]
添加了比较粗略的部署文档，写了一些注意点，比如要配置cookie作用域还有nginx的配置，如果还有问题的话可以提

**Comment by awxiaoxian2020** [comment]
Thanks!
